// Code generated by taskw. DO NOT EDIT.

package api

import (
	"github.com/example/ecommerce-api/internal/order"
	"github.com/example/ecommerce-api/internal/product"
	"github.com/example/ecommerce-api/internal/user"
	"github.com/google/wire"
)

// GeneratedProviderSet contains all discovered Provide* functions
var GeneratedProviderSet = wire.NewSet(

	// order module providers
	order.ProvideHandler,
	order.ProvideRepository,
	order.ProvideService,

	// product module providers
	product.ProvideHandler,
	product.ProvideRepository,
	product.ProvideService,

	// user module providers
	user.ProvideHandler,
	user.ProvideRepository,
	user.ProvideService,
)
