// This file will be generated by taskw
// Run 'taskw generate deps' to create this file

package api

import "github.com/google/wire"

// This is a placeholder - taskw will replace this entire file
var GeneratedProviderSet = wire.NewSet(
// Placeholder - this should cause a compilation error until taskw generates the real content
// TaskW will scan for Provide* functions and generate the real provider set
)

// Expected generated content after running 'taskw generate deps':
//
// var GeneratedProviderSet = wire.NewSet(
//     // User module providers (from Provide* functions)
//     user.ProvideRepository,
//     user.ProvideService,
//     user.ProvideHandler,
//
//     // Product module providers (from Provide* functions)
//     product.ProvideRepository,
//     product.ProvideService,
//     product.ProvideHandler,
//
//     // Order module providers (from Provide* functions)
//     order.ProvideRepository,
//     order.ProvideService,
//     order.ProvideHandler,
// )
