// Code generated by taskw. DO NOT EDIT.

package api

import (
	"github.com/gofiber/fiber/v2"
)

// RegisterRoutes registers all HTTP routes with the Fiber app
func (s *Server) RegisterRoutes(app *fiber.App) {
	app.Get("/api/v1/products/:id/stock", s.productHandler.CheckStock)
	app.Get("/api/v1/users/:user_id/orders", s.orderHandler.GetUserOrders)
	app.Post("/api/v1/orders/:id/cancel", s.orderHandler.CancelOrder)
	app.Put("/api/v1/orders/:id/status", s.orderHandler.UpdateOrderStatus)
	app.Get("/api/v1/users/by-email", s.userHandler.GetUserByEmail)
	app.Delete("/api/v1/products/:id", s.productHandler.DeleteProduct)
	app.Delete("/api/v1/users/:id", s.userHandler.DeleteUser)
	app.Get("/api/v1/orders/:id", s.orderHandler.GetOrder)
	app.Get("/api/v1/products/:id", s.productHandler.GetProduct)
	app.Get("/api/v1/users/:id", s.userHandler.GetUser)
	app.Put("/api/v1/products/:id", s.productHandler.UpdateProduct)
	app.Put("/api/v1/users/:id", s.userHandler.UpdateUser)
	app.Get("/api/v1/categories", s.productHandler.GetCategories)
	app.Get("/api/v1/orders", s.orderHandler.GetOrders)
	app.Get("/api/v1/products", s.productHandler.GetProducts)
	app.Get("/api/v1/users", s.userHandler.GetUsers)
	app.Post("/api/v1/orders", s.orderHandler.CreateOrder)
	app.Post("/api/v1/products", s.productHandler.CreateProduct)
	app.Post("/api/v1/users", s.userHandler.CreateUser)
	app.Get("/health", s.healthHandler.GetHealth)

	s.logger.Info("All routes registered successfully")
}
