// This file will be generated by taskw
// Run 'taskw generate routes' to create this file

package api

import "github.com/gofiber/fiber/v2"

// This is a placeholder - taskw will replace this entire file
func (s *Server) RegisterRoutes(app *fiber.App) {
	s.logger.Fatal("Routes not generated yet! Run 'taskw generate routes' to create route registration.")
}

// Expected generated content after running 'taskw generate routes':
//
// func (s *Server) RegisterRoutes(app *fiber.App) {
//     api := app.Group("/api/v1")
//
//     // User routes (from @Router annotations)
//     api.Get("/users", s.userHandler.GetUsers)
//     api.Get("/users/:id", s.userHandler.GetUser)
//     api.Post("/users", s.userHandler.CreateUser)
//     api.Put("/users/:id", s.userHandler.UpdateUser)
//     api.Delete("/users/:id", s.userHandler.DeleteUser)
//     api.Get("/users/by-email", s.userHandler.GetUserByEmail)
//     api.Get("/users/:user_id/orders", s.orderHandler.GetUserOrders)
//
//     // Product routes (from @Router annotations)
//     api.Get("/products", s.productHandler.GetProducts)
//     api.Get("/products/:id", s.productHandler.GetProduct)
//     api.Post("/products", s.productHandler.CreateProduct)
//     api.Put("/products/:id", s.productHandler.UpdateProduct)
//     api.Delete("/products/:id", s.productHandler.DeleteProduct)
//     api.Get("/products/:id/stock", s.productHandler.CheckStock)
//
//     // Category routes (from @Router annotations)
//     api.Get("/categories", s.productHandler.GetCategories)
//
//     // Order routes (from @Router annotations)
//     api.Get("/orders", s.orderHandler.GetOrders)
//     api.Get("/orders/:id", s.orderHandler.GetOrder)
//     api.Post("/orders", s.orderHandler.CreateOrder)
//     api.Put("/orders/:id/status", s.orderHandler.UpdateOrderStatus)
//     api.Post("/orders/:id/cancel", s.orderHandler.CancelOrder)
//
//     s.logger.Info("All routes registered successfully")
// }
