// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/example/ecommerce-api/internal/health"
	"github.com/example/ecommerce-api/internal/logger"
	"github.com/example/ecommerce-api/internal/order"
	"github.com/example/ecommerce-api/internal/product"
	"github.com/example/ecommerce-api/internal/user"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeServer initializes the complete server with all dependencies
func InitializeServer() (*Server, error) {
	zapLogger, err := logger.ProvideLogger()
	if err != nil {
		return nil, err
	}
	repository := health.ProvideRepository()
	service := health.ProvideService(repository)
	handler := health.ProvideHandler(service)
	userRepository := user.ProvideRepository()
	userService := user.ProvideService(userRepository)
	userHandler := user.ProvideHandler(userService)
	productRepository := product.ProvideRepository()
	productService := product.ProvideService(productRepository)
	productHandler := product.ProvideHandler(productService)
	orderRepository := order.ProvideRepository()
	orderProductService := ProvideProductServiceAdapter(productService)
	orderUserService := ProvideUserServiceAdapter(userService)
	orderService := order.ProvideService(orderRepository, orderProductService, orderUserService)
	orderHandler := order.ProvideHandler(orderService)
	server := ProvideServer(zapLogger, handler, userHandler, productHandler, orderHandler)
	return server, nil
}

// wire.go:

// ProviderSet will be augmented by taskw generated dependencies
// This only contains infrastructure providers - taskw will add the rest
var ProviderSet = wire.NewSet(

	GeneratedProviderSet,
)
