// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/example/ecommerce-api/internal/health"
	"github.com/example/ecommerce-api/internal/order"
	"github.com/example/ecommerce-api/internal/product"
	"github.com/example/ecommerce-api/internal/user"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeRouter() (*Router, error) {
	app := ProvideFiberApp()
	repository := health.ProvideRepository()
	service := health.ProvideService(repository)
	handler := health.ProvideHandler(service)
	orderRepository := order.ProvideRepository()
	productRepository := product.ProvideRepository()
	productService := product.ProvideService(productRepository)
	orderProductService := ProvideProductServiceAdapter(productService)
	userRepository := user.ProvideRepository()
	userService := user.ProvideService(userRepository)
	orderUserService := ProvideUserServiceAdapter(userService)
	orderService := order.ProvideService(orderRepository, orderProductService, orderUserService)
	orderHandler := order.ProvideHandler(orderService)
	productHandler := product.ProvideHandler(productService)
	userHandler := user.ProvideHandler(userService)
	router := ProvideRouter(app, handler, orderHandler, productHandler, userHandler)
	return router, nil
}

// wire.go:

// ProviderSet will be augmented by taskw generated dependencies
// This only contains infrastructure providers - taskw will add the rest
var ProviderSet = wire.NewSet(

	GeneratedProviderSet,
)
