// Code generated by taskw. DO NOT EDIT.

package cli

import (
	"github.com/google/wire"
	"github.com/nkaewam/taskw/internal/cli/clean"
	"github.com/nkaewam/taskw/internal/cli/file"
	"github.com/nkaewam/taskw/internal/cli/generation"
	"github.com/nkaewam/taskw/internal/cli/project"
	"github.com/nkaewam/taskw/internal/cli/scan"
	"github.com/nkaewam/taskw/internal/cli/ui"
	"github.com/nkaewam/taskw/internal/config"
)

// GeneratedProviderSet contains all discovered Provide* functions
var GeneratedProviderSet = wire.NewSet(

	// clean module providers
	clean.ProvideCleanService,

	// config module providers
	config.ProvideConfig,

	// file module providers
	file.ProvideFileService,

	// generation module providers
	generation.ProvideGenerationService,

	// project module providers
	project.ProvideProjectService,

	// scan module providers
	scan.ProvideScanService,

	// ui module providers
	ui.ProvideUIService,
)
